/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD_vista;

import controlador.controlador;
import datos.ClsVendedorJDBC;
import dominio.ClsVendedores;

/**
 *
 * @author Win10
 */
public class VendedoresFMR extends javax.swing.JFrame {

    /**
     * Creates new form VendedoresFMR
     */
    private ClsVendedorJDBC vende = new ClsVendedorJDBC();
    public VendedoresFMR() {
        initComponents();
        this.setTitle("Vendedores");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_cod = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_ene = new javax.swing.JTextField();
        txt_feb = new javax.swing.JTextField();
        txt_mar = new javax.swing.JTextField();
        btn_crear = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_listar = new javax.swing.JButton();
        btn_eliminar1 = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("VENDEDORES");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Código:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Venta de enero:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Venta de febrero:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Venta de marzo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txt_cod.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_cod.setToolTipText("");
        jPanel1.add(txt_cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 180, -1));

        txt_name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_name.setToolTipText("");
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 180, -1));

        txt_ene.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_ene.setToolTipText("");
        txt_ene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_eneActionPerformed(evt);
            }
        });
        jPanel1.add(txt_ene, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 180, -1));

        txt_feb.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_feb.setToolTipText("");
        jPanel1.add(txt_feb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 180, -1));

        txt_mar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_mar.setToolTipText("");
        jPanel1.add(txt_mar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 180, -1));

        btn_crear.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_crear.setText("CREAR");
        btn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 100, -1));

        btn_actualizar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_actualizar.setText("ACTUALIZAR");
        jPanel1.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 100, -1));

        btn_listar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_listar.setText("LISTAR");
        jPanel1.add(btn_listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 100, -1));

        btn_eliminar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_eliminar1.setText("ELIMINAR");
        jPanel1.add(btn_eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 100, -1));

        btn_editar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_editar.setText("EDITAR");
        jPanel1.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 210));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TABLA.setBackground(new java.awt.Color(204, 255, 255));
        TABLA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "ENERO", "FEBRERO", "MARZO", "TOTAL", "PROMEDIO"
            }
        ));
        jScrollPane1.setViewportView(TABLA);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 220));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 500, 230));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 500, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
        
    }//GEN-LAST:event_btn_crearActionPerformed

    private void txt_eneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_eneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_eneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       VendedoresFMR vista = new VendedoresFMR();
       controlador c = new controlador(vista);
       vista.setVisible(true);
       vista.setLocationRelativeTo(vista);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TABLA;
    public javax.swing.JButton btn_actualizar;
    public javax.swing.JButton btn_crear;
    public javax.swing.JButton btn_editar;
    public javax.swing.JButton btn_eliminar1;
    public javax.swing.JButton btn_listar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField txt_cod;
    public javax.swing.JTextField txt_ene;
    public javax.swing.JTextField txt_feb;
    public javax.swing.JTextField txt_mar;
    public javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
